In [45]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from konlpy.tag import Twitter

import pandas as pd
import pickle


#### Load Dataset
    0: 정치 , 1: 경제, 2: 사회, 3: 생활/문화, 4: 세계, 5: IT/과학

In [46]:
article_df = pd.read_pickle("article_2016-06-01.plk")
print(len(article_df))
article_df.tail()

2327


newsid  oid newspaper                                          title  \
2322  2976863   20      동아일보              中, 원자재서 첨단기술로 ‘사냥 타깃’ 이동… 한국은 제자리   
2323  2976847   20      동아일보                       "왓슨 한국어 배우는 중… 연내 데뷔 가능"   
2324  3179706   23      조선일보  [어수웅의 르네상스人] 종이 사전을 삼킨 남자, &#39;웹 사전&#39;을 낳다   
2325  2976797   20      동아일보                     中, M&A로 특허 포식… 한국 미래산업 삼킨다   
2326  2620983   25      중앙일보                      구글·애플 대항마…토종 앱 장터 원스토어 떴다   

                                                   link  comment  likeit  \
2322  http://news.naver.com/main/read.nhn?mode=LSD&m...        5       4   
2323  http://news.naver.com/main/read.nhn?mode=LSD&m...        1       4   
2324  http://news.naver.com/main/read.nhn?mode=LSD&m...        0       2   
2325  http://news.naver.com/main/read.nhn?mode=LSD&m...       13       9   
2326  http://news.naver.com/main/read.nhn?mode=LSD&m...      123       9   

                                                content        date  category  
2322  [동아일보][미래산업 먹어치우는 중국]슈퍼 포식자 중국美 로봇업체 인수… 獨기업 눈...  2016-06-01         5  
2323  [동아일보][2016 동아 국제금융 포럼]‘AI 전문가’ 메네제스 IBM 부사장“A...  2016-06-01         5  
2324  [정철 카카오 웹 사전 기획자] 책 '검색, 사전을 삼키다' 펴내… 연세대에서 사전...  2016-06-01         5  
2325  [동아일보]中, 로봇-IoT-바이오 등 M&A; 규모… 올해 5월에 이미 작년 기록...  2016-06-01         5  
2326  이통 3사, 네이버 손잡고 시장 40% 점유 목표| 양강 구도에 도전장…앱 생태계 ...  2016-06-01         5

#### Split Train, Test

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ["This is very strange",
          "This is very nice"]
vectorizer = TfidfVectorizer(min_df=1)
X = vectorizer.fit_transform(corpus)
idf = vectorizer.idf_
idf

array([1.        , 1.40546511, 1.40546511, 1.        , 1.        ])

In [48]:
X_train, X_test, y_train, y_test = train_test_split(article_df.content, article_df.category, \
                                                    test_size = 0.1, random_state =1)
#10%를 테스트로


In [53]:
a = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', MultinomialNB(alpha=0.01)) # alpha -> 스무딩
])
model = a.fit(X_train, y_train)

In [50]:
X_test

579     인천 송도 삼성바이오로직스 현장을 가다“삼성이 처음 핸드폰 사업을 시작할 때 망치로...
1355    [구의역 사고를 보며] 청년을 위한 나라는 없다 [ 주동식 지역평등시민연대 대표] ...
47       [한겨레] 구의역·남양주 사고에 입법대책 분주더민주, 직접 고용법 제정안 발의국민...
1118    김종인 롯데마트 대표이사가 지난 4월 18일 오전 서울 중구 롯데호텔에서 열린 '가...
614     [서울신문]자동차 연료 따라 보험료 차등화… LPG·하이브리드는 더 오를 듯보험업계...
108     [앵커] 잇따른 미사일 시험발사 실패로 체면을 구긴 북한이 자신들이 성공했다고 주장...
6        [한겨레] 3년여 만에 북 고위급 면담“지역 평화안정 보호하길” 역설리수용, 김정...
2275    [머니투데이 김희정 기자] [옥타코어 프로세서로 속도 향상… 후면카메라 1600만 ...
1179        (수원=연합뉴스) 최찬흥 기자 = 경기도가 남양주 진접선 지하철 공사현장 폭...
2317    - 가격은 기존 대리운전 업체보다 비싸지만 편의성·안전성↑- 소속 대리운전 기사 만...
2121    BBC 사진 캡처웨스트미들랜드 스탠퍼드카운티대, 도자기 270점 소장    (서울=...
576     신도시·택지지구 공급물량 완판 행진서울 도심권에 비해 높은 수익률 기대김포한강·동탄...
644     <아이뉴스24>[김두탁기자] 10년 이상 경력직 채용 희망기업을 조사한 결과, 연봉...
17      북한 손 들어줄까 내심 우려 “비핵화 없인 국면 변화 난망…김정은 방중도 어려울 것...
2095    중국 인권 사이트 웨이취안왕(維權網) 사진 캡처    (서울=연합뉴스) 조성대 기자...
1163    불용재고의약품 문제를 놓고 추무진 대한의사협회장과 조찬휘 대한약사회장이 설전을 벌였...
403     ㆍ새누리당 김종석 당선인, 평생직장에서 평생고용으로 전환 강조김종석 당선자는? 프린...
1868    자전거 퍼레

In [51]:
vect = TfidfVectorizer()
vect.fit(X_train)
obj = vect.transform(X_train)

In [52]:
model = MultinomialNB(alpha=0.01).fit(obj, y_train)

#### Confusion Matrix, Classification Report

In [54]:
from sklearn.metrics import confusion_matrix, classification_report 

In [55]:
objtest = vect.transform(X_test)
y_pred = model.predict(X_test)


In [56]:
y_pred

array([1, 2, 0, 2, 3, 0, 0, 5, 2, 5, 2, 1, 1, 0, 2, 2, 0, 2, 0, 2, 2, 2,
       1, 2, 5, 2, 1, 4, 2, 3, 2, 1, 2, 2, 0, 2, 2, 2, 0, 2, 1, 1, 2, 0,
       0, 0, 0, 4, 2, 2, 1, 3, 3, 4, 1, 4, 4, 2, 0, 2, 2, 0, 2, 2, 3, 4,
       0, 2, 0, 1, 0, 0, 4, 1, 3, 0, 0, 0, 2, 4, 0, 4, 3, 0, 1, 4, 5, 2,
       4, 3, 3, 5, 2, 0, 1, 5, 2, 1, 0, 2, 1, 1, 3, 2, 0, 2, 2, 2, 4, 4,
       2, 2, 0, 4, 1, 5, 5, 1, 2, 3, 2, 4, 2, 2, 2, 1, 4, 2, 4, 2, 2, 2,
       4, 3, 3, 0, 1, 2, 2, 3, 2, 0, 2, 1, 2, 2, 0, 1, 0, 0, 4, 0, 3, 1,
       4, 2, 4, 4, 0, 2, 2, 3, 1, 2, 5, 0, 0, 1, 4, 2, 0, 3, 2, 3, 0, 3,
       1, 0, 2, 3, 1, 0, 3, 2, 2, 1, 2, 4, 1, 5, 4, 0, 2, 1, 2, 3, 2, 4,
       1, 2, 0, 0, 3, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 5, 2, 1, 2, 1, 2, 2,
       1, 0, 3, 2, 1, 2, 5, 2, 2, 1, 2, 5, 4])

In [57]:
objtest

<233x136803 sparse matrix of type '<class 'numpy.float64'>'
	with 43709 stored elements in Compressed Sparse Row format>

In [58]:
confusion_matrix(y_test, y_pred)

array([[41,  0,  3,  1,  1,  0],
       [ 1, 33,  0,  5,  1,  1],
       [ 1,  2, 77,  2,  1,  0],
       [ 0,  0,  2, 18,  0,  1],
       [ 1,  1,  2,  0, 25,  0],
       [ 0,  1,  1,  0,  0, 11]])

In [59]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.93      0.89      0.91        46
          1       0.89      0.80      0.85        41
          2       0.91      0.93      0.92        83
          3       0.69      0.86      0.77        21
          4       0.89      0.86      0.88        29
          5       0.85      0.85      0.85        13

avg / total       0.88      0.88      0.88       233



#### Prediction

In [60]:
X_test = X_test.reset_index(drop = True)
X_test[0][:100], X_test[1][:100], X_test[2][:100]

('인천 송도 삼성바이오로직스 현장을 가다“삼성이 처음 핸드폰 사업을 시작할 때 망치로 핸드폰을 깨부수는 등 온갖 실험을 했던 동영상도 보여주며 ‘이렇게 시작해 휴대폰 사업도 성공했다',
 '[구의역 사고를 보며] 청년을 위한 나라는 없다\xa0[ 주동식 지역평등시민연대 대표]\xa0요즘 사람의 실제 나이는 전통적인 개념의 숫자에 0.8을 곱해서 계산해야 한다고 한다. 50세 중',
 ' [한겨레] 구의역·남양주 사고에 입법대책 분주더민주, 직접 고용법 제정안 발의국민의당, 청년고용할당제 확대정의당도 ‘기업살인법’ 발의키로정부·여당 반대로 통과 어려울듯새누리, 야')

In [12]:
X_test

0      인천 송도 삼성바이오로직스 현장을 가다“삼성이 처음 핸드폰 사업을 시작할 때 망치로...
1      [구의역 사고를 보며] 청년을 위한 나라는 없다 [ 주동식 지역평등시민연대 대표] ...
2       [한겨레] 구의역·남양주 사고에 입법대책 분주더민주, 직접 고용법 제정안 발의국민...
3      김종인 롯데마트 대표이사가 지난 4월 18일 오전 서울 중구 롯데호텔에서 열린 '가...
4      [서울신문]자동차 연료 따라 보험료 차등화… LPG·하이브리드는 더 오를 듯보험업계...
5      [앵커] 잇따른 미사일 시험발사 실패로 체면을 구긴 북한이 자신들이 성공했다고 주장...
6       [한겨레] 3년여 만에 북 고위급 면담“지역 평화안정 보호하길” 역설리수용, 김정...
7      [머니투데이 김희정 기자] [옥타코어 프로세서로 속도 향상… 후면카메라 1600만 ...
8          (수원=연합뉴스) 최찬흥 기자 = 경기도가 남양주 진접선 지하철 공사현장 폭...
9      - 가격은 기존 대리운전 업체보다 비싸지만 편의성·안전성↑- 소속 대리운전 기사 만...
10     BBC 사진 캡처웨스트미들랜드 스탠퍼드카운티대, 도자기 270점 소장    (서울=...
11     신도시·택지지구 공급물량 완판 행진서울 도심권에 비해 높은 수익률 기대김포한강·동탄...
12     <아이뉴스24>[김두탁기자] 10년 이상 경력직 채용 희망기업을 조사한 결과, 연봉...
13     북한 손 들어줄까 내심 우려 “비핵화 없인 국면 변화 난망…김정은 방중도 어려울 것...
14     중국 인권 사이트 웨이취안왕(維權網) 사진 캡처    (서울=연합뉴스) 조성대 기자...
15     불용재고의약품 문제를 놓고 추무진 대한의사협회장과 조찬휘 대한약사회장이 설전을 벌였...
16     ㆍ새누리당 김종석 당선인, 평생직장에서 평생고용으로 전환 강조김종석 당선자는? 프린...
17     자전거 퍼레이드 행사 구간[서울시 제공]  

In [61]:
result = model.predict([X_test[0],X_test[1],X_test[2] ])
result

array([1, 2, 0])

In [62]:
classification_dict = {
    0:"정치", 1:"경제", 2:"사회", 3:"생활/문화", 4:"세계", 5:"IT/과학",
}

for idx, category in enumerate(result):
    print(classification_dict[category], X_test[idx][:50])

경제 인천 송도 삼성바이오로직스 현장을 가다“삼성이 처음 핸드폰 사업을 시작할 때 망치로 핸드폰
사회 [구의역 사고를 보며] 청년을 위한 나라는 없다 [ 주동식 지역평등시민연대 대표] 요즘 사
정치  [한겨레] 구의역·남양주 사고에 입법대책 분주더민주, 직접 고용법 제정안 발의국민의당, 


#### Save & Load Model

In [63]:
pickle.dump(model, open("classification.plk", "wb"))

In [64]:
load_model = pickle.load(open('classification.plk', 'rb'))

In [66]:
str1 = "카라멜 마끼아또 먹는 아이폰은 2호선을 타고 집에 간다"
str2 = "취업난에 허덕이는 이삼십대 인구수가 점점 더 증가하고 있다"
load_model.predict([str1, str2])

array([3, 2])

In [67]:
load_model.predict_proba([str1, str2])

array([[0.13706888, 0.05622285, 0.1944603 , 0.43522812, 0.12537453,
        0.05164532],
       [0.06214966, 0.28150937, 0.33569717, 0.09510242, 0.13618774,
        0.08935364]])